### ISSUE TITLE
==> ERROR: install file (modular.install) does not exist or is not a regular file. /bin/sh: line 1: modular: command not found Failed to authenticate modular using token: ''

### ISSUE THREAD

**Issue by musram** [Sharktheone/arch-mojo#21]
I am using arch linux.

I used python <(curl -sSL https://raw.githubusercontent.com/Sharktheone/arch-mojo/main/src/install.py)  but got the error
==> ERROR: install file (modular.install) does not exist or is not a regular file.
/bin/sh: line 1: modular: command not found
Failed to authenticate modular using token: ''

**Comment by Sharktheone** [comment]
That's interesting... I'll take a look on that. Do you have an aur helper installed? You can use the `mojo` package to install modular and mojo on your system

**Comment by musram** [comment]
Yes. I will install it using yay.

Regards,
Sai
