### ISSUE TITLE
Error: Shell /bin/fish not supported

### ISSUE THREAD

**Issue by max2000warlord** [Sharktheone/arch-mojo#23]
Just submitted a pull request that adds support for fish.

**Comment by graytonio** [comment]
The AUR build has not been updated yet I am still getting fish not a supported shell

**Comment by Sharktheone** [comment]
Oh, yeah... totally forgot about that. I'll try to do it soon™

**Comment by Sharktheone** [comment]
Should be fixed in `mojo-libs 0.1-3`
