### ISSUE TITLE
Working with Jupyter notebook

### ISSUE THREAD

**Issue by hajsf** [Sharktheone/arch-mojo#4]
I'm not sure where shall I post this, but thought this repo may be the most proper one.
After installing mojo ar archcraft using this repo and getting it running, I was able to access the mojo kernel through the jupyter notebook as well, but once I tried accessing the same kernel through jupyter plugin in the VS code I got the error: 
`OSError: libpanel.so.6: cannot open shared object file: No such file or directory. `  as hown in the screenshoot below:

![image](https://github.com/Sharktheone/arch-mojo/assets/98168280/70474df6-2a95-4420-91f5-52872e623a55)

**Comment by Sharktheone** [comment]
This is probably because VSCode does not use your `~/.zshrc` or `~/.bashrc`. 
You can try adding `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.local/lib/mojo`  to your `/etc/profile` or `/etc/environment`

**Comment by hajsf** [comment]
> /etc/profile

now the `/etctprofile` is:
```profile
append_path () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

# Append our default paths
append_path '/usr/local/sbin'
append_path '/usr/local/bin'
append_path '/usr/bin'

# Force PATH to be environment
export PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.local/lib/mojo
```

And I made `source /etc/profile`, cloded VS code and opned it again, but still the same

**Comment by Sharktheone** [comment]
I think when you edit `/etc/profile` the easiest is rebooting your machine

**Comment by hajsf** [comment]
> rebooting your machine
Thanks  a lot, is fine now

![image](https://github.com/Sharktheone/arch-mojo/assets/98168280/fbee3538-d574-4294-9989-d2252a31cb27)
