### ISSUE TITLE
Issue with the symbolic links for the libraries used globally

### ISSUE THREAD

**Issue by hajsf** [Sharktheone/arch-mojo#7]
Hi, As I mentioned before the script is working fine with me, I installed it in multiple tries, and all are fine, but just once once I read the code, I understood the reason why out of the sudden I started getting the below everytime I install or remove an app, it looks it is related to this installation code:

```bash
(1/1) removing go                                                                  [###############################################] 100%
ldconfig: /usr/lib/libpanel.so.6 is not a symbolic link

ldconfig: /usr/lib/libmenu.so.6 is not a symbolic link

ldconfig: /usr/lib/libform.so.6 is not a symbolic link

ldconfig: /usr/lib/libedit.so.2 is not a symbolic link

ldconfig: /usr/lib/libncurses.so.6 is not a symbolic link
```

I was able to fix this by:
1. Remove the existing non-symbolic link files as:
```bash
sudo rm libpanel.so.6 libmenu.so.6 libform.so.6 libedit.so.2 libncurses.so.6
```

2. Recreating symbolic links using the ln command:
```bash
sudo ln -s libpanel.so.6.0 libpanel.so.6
sudo ln -s libmenu.so.6.0 libmenu.so.6
sudo ln -s libform.so.6.0 libform.so.6
sudo ln -s libedit.so.2.0 libedit.so.2
sudo ln -s libncurses.so.6.0 libncurses.so.6
```
3. After recreating the symbolic links, running `ldconfig` to update the library cache, as:
```
sudo ldconfig
```

Can you fix the code to handle this properly?

**Note**
I asked the same to ChatGPT, and it proposed the below:
```python
import os
import shutil
import subprocess
import sys
import urllib.request

# ... (previous code)

# Function to create symbolic links for shared libraries
def create_symbolic_links(lib_name, lib_version, lib_path):
    lib_file = f"{lib_name}.so.{lib_version}"
    lib_link = f"{lib_name}.so.{lib_version.split('-')[0] or lib_version}"
    lib_full_path = f"{lib_path}/{lib_file}"

    # Check if the symbolic link already exists
    if not os.path.exists(f"{lib_path}/{lib_link}"):
        os.system(f"sudo ln -s {lib_full_path} {lib_path}/{lib_link}")

# ... (previous code)

# copy libs
if install_global:
    os.system(f"sudo cp {WORKING_DIR}lib/{arch}/* /lib/")
    os.system(f"sudo cp {WORKING_DIR}usr/lib/{arch}/* /usr/lib/")
    os.system(f"sudo cp {WORKING_DIR}lib/{arch}/* /usr/lib/")
else:
    os.system(f"mkdir -p {mojo_lib_path}")

    os.system(f"cp {WORKING_DIR}lib/{arch}/libncurses.so.6.4 {mojo_lib_path}/libncurses.so.6")
    os.system(f"cp {WORKING_DIR}/usr/lib/{arch}/libform.so.6.4 {mojo_lib_path}/libform.so.6")
    os.system(f"cp {WORKING_DIR}/usr/lib/{arch}/libpanel.so.6.4 {mojo_lib_path}/libpanel.so.6")
    os.system(f"cp {WORKING_DIR}/usr/lib/{arch}/libedit.so.2.0.70 {mojo_lib_path}/libedit.so.2")

    # Create symbolic links for shared libraries
    create_symbolic_links("libncurses", "6.4-4", mojo_lib_path)
    create_symbolic_links("libform", "6.4", mojo_lib_path)
    create_symbolic_links("libpanel", "6.4", mojo_lib_path)
    create_symbolic_links("libedit", "2.0.70", mojo_lib_path)

# ... (rest of the code)
```

**Comment by Sharktheone** [comment]
Okay, I actually haven't tested the global installation method. I think, I may remove that one. But thanks for the issue!

**Comment by mikkelrask** [comment]
I removed the `export PATH=...` lines that was added in my `.zshrc` file.. Could easily use curses apps after doing so and restarting my terminal.

**Comment by Sharktheone** [comment]
The `export PATH=...` should only tell your shell, where it finds the modular and mojo binaries (and some others), so you'd probably mean the `LD_LIBRARY_PATH`?

For me, curse apps work with and without the exports normally (tested with glances)

**Comment by hajsf** [comment]
> The `export PATH=...` should only tell your shell, where it finds the modular and mojo binaries (and some others), so you'd probably mean the `LD_LIBRARY_PATH`?
> 
> For me, curse apps work with and without the exports normally (tested with glances)

mm, thanks for the feedback, but I did not get what shall I do :(

**Comment by Sharktheone** [comment]
> mm, thanks for the feedback, but I did not get what shall I do :(

This was more meant for the comment from @mikkelrask. You only need to update the script, there it sould be fixed. Maybe you need to delete the old links.
